---
title: Metadatenprofile für Survey Content Package
---

ID of profile-store: `scp`

Creator: IQB - Institut zur Qualitätsentwicklung im Bildungswesen

3 Profile definiert:

# Survey Content Package Index

ID of profile: `https://raw.githubusercontent.com/iqb-vocabs/p44/master/index.json`

| Name/Label | Typ | Parameter | ID Profil-Eintrag |
| :--- | :---: | :--- | :---: |
| Art der Erhebung | [Vokabular](https://w3id.org/iqb/v85/dt/) | url: 'https://w3id.org/iqb/v85/dt/', Mehrfachauswahl, Dialogbox, Nummerierung unterdrückt | e1 |
| Schulform | [Vokabular](https://w3id.org/kim/schularten/) | url: 'https://w3id.org/kim/schularten/', Einmalauswahl, Dialogbox, Nummerierung unterdrückt | kim_type_school |
| Untersuchungsdesign | [Vokabular](https://w3id.org/iqb/v85/ed/) | url: 'https://w3id.org/iqb/v85/ed/', Einmalauswahl, Dialogbox, Nummerierung unterdrückt | e4 |
| Erhebungsverfahren | [Vokabular](https://w3id.org/iqb/v85/v2/) | url: 'https://w3id.org/iqb/v85/v2/', Mehrfachauswahl, Dialogbox, Nummerierung unterdrückt | e5 |
| Erhebungseinheit | [Vokabular](https://w3id.org/iqb/v85/ee/) | url: 'https://w3id.org/iqb/v85/ee/', Mehrfachauswahl, Dialogbox | e6 |

: {tbl-colwidths="[15,15,55,15]"}

# Survey Content Package Part

ID of profile: `https://raw.githubusercontent.com/iqb-vocabs/p44/master/surveyPart.json`

| Name/Label | Typ | Parameter | ID Profil-Eintrag |
| :--- | :---: | :--- | :---: |
| Klassenstufe | [Vokabular](http://w3id.org/openeduhub/vocabs/educationalLevel/) | url: 'http://w3id.org/openeduhub/vocabs/educationalLevel/', Mehrfachauswahl, Dialogbox, Nummerierung unterdrückt | f0 |
| Für SPF geeignet | Ja/Nein | Text für WAHR: ja, Text für FALSCH: nein | f23 |
| Art der Erhebung | [Vokabular](https://w3id.org/iqb/v85/dt/) | url: 'https://w3id.org/iqb/v85/dt/', Mehrfachauswahl, Dialogbox, Nummerierung unterdrückt | f1 |
| Untersuchungsdesign | [Vokabular](https://w3id.org/iqb/v85/ed/) | url: 'https://w3id.org/iqb/v85/ed/', Einmalauswahl, Dialogbox, Nummerierung unterdrückt | f4 |
| Erhebungseinheit | [Vokabular](https://w3id.org/iqb/v85/ee/) | url: 'https://w3id.org/iqb/v85/ee/', Mehrfachauswahl, Dialogbox | f6 |

: {tbl-colwidths="[15,15,55,15]"}

# Survey Content Package Instrument

ID of profile: `https://raw.githubusercontent.com/iqb-vocabs/p44/master/instrument.json`

| Name/Label | Typ | Parameter | ID Profil-Eintrag |
| :--- | :---: | :--- | :---: |
| Klassenstufe | [Vokabular](http://w3id.org/openeduhub/vocabs/educationalLevel/) | url: 'http://w3id.org/openeduhub/vocabs/educationalLevel/', Mehrfachauswahl, Dialogbox, Nummerierung unterdrückt | f0 |
| Für SPF geeignet | Ja/Nein | Text für WAHR: ja, Text für FALSCH: nein | f23 |
| Art der Erhebung | [Vokabular](https://w3id.org/iqb/v85/dt/) | url: 'https://w3id.org/iqb/v85/dt/', Mehrfachauswahl, Dialogbox, Nummerierung unterdrückt | f1 |
| Untersuchungsdesign | [Vokabular](https://w3id.org/iqb/v85/ed/) | url: 'https://w3id.org/iqb/v85/ed/', Einmalauswahl, Dialogbox, Nummerierung unterdrückt | f4 |
| Erhebungseinheit | [Vokabular](https://w3id.org/iqb/v85/ee/) | url: 'https://w3id.org/iqb/v85/ee/', Mehrfachauswahl, Dialogbox | f6 |

: {tbl-colwidths="[15,15,55,15]"}

